//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGCA.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGCA.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para que a pesquisa seja realizada, é necessário que preencher o campo Data de Envio.
        /// </summary>
        public static string common_error_um_campo_necessario_para_consulta_baixa_processamento {
            get {
                return ResourceManager.GetString("common_error_um_campo_necessario_para_consulta_baixa_processamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente limpar o Formulário? (sim /não).
        /// </summary>
        public static string confirmacao_limpar_formulario {
            get {
                return ResourceManager.GetString("confirmacao_limpar_formulario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair? (sim /não).
        /// </summary>
        public static string confirmacao_sair {
            get {
                return ResourceManager.GetString("confirmacao_sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso inválido! Tente novamente..
        /// </summary>
        public static string erro_acesso_invalido {
            get {
                return ResourceManager.GetString("erro_acesso_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha é de preenchimento obrigatório..
        /// </summary>
        public static string erro_captcha_obrigatorio {
            get {
                return ResourceManager.GetString("erro_captcha_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O texto digitado não corresponde a imagem!.
        /// </summary>
        public static string erro_codigo_invalido {
            get {
                return ResourceManager.GetString("erro_codigo_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da nova senha é de preenchimento obrigatório..
        /// </summary>
        public static string erro_confirmacao_nova_senha_obrigatoria {
            get {
                return ResourceManager.GetString("erro_confirmacao_nova_senha_obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados estão incorretos..
        /// </summary>
        public static string erro_dados_incorretos {
            get {
                return ResourceManager.GetString("erro_dados_incorretos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail é de preenchimento obrigatório..
        /// </summary>
        public static string erro_email_obrigatorio {
            get {
                return ResourceManager.GetString("erro_email_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou e-mail incorretos..
        /// </summary>
        public static string erro_login_email_incorretos {
            get {
                return ResourceManager.GetString("erro_login_email_incorretos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login é de preenchimento obrigatório..
        /// </summary>
        public static string erro_login_obrigatorio {
            get {
                return ResourceManager.GetString("erro_login_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login é de preenchimento obrigatório..
        /// </summary>
        public static string erro_login_obrigatorio1 {
            get {
                return ResourceManager.GetString("erro_login_obrigatorio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova senha é de preenchimento obrigatório..
        /// </summary>
        public static string erro_nova_senha_obrigatoria {
            get {
                return ResourceManager.GetString("erro_nova_senha_obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Incorreta..
        /// </summary>
        public static string erro_senha_incorreta {
            get {
                return ResourceManager.GetString("erro_senha_incorreta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha é de preenchimento obrigatório..
        /// </summary>
        public static string erro_senha_obrigatoria {
            get {
                return ResourceManager.GetString("erro_senha_obrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da nova senha deve ter entre 6 e 20 caracteres..
        /// </summary>
        public static string erro_tamanho_confirmacao_nova_senha_min_max {
            get {
                return ResourceManager.GetString("erro_tamanho_confirmacao_nova_senha_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo E-mail excedeu o tamanho limite de caracteres!.
        /// </summary>
        public static string erro_tamanho_email {
            get {
                return ResourceManager.GetString("erro_tamanho_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Login excedeu o tamanho limite de caracteres!.
        /// </summary>
        public static string erro_tamanho_login {
            get {
                return ResourceManager.GetString("erro_tamanho_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Login excedeu o tamanho limite de caracteres!.
        /// </summary>
        public static string erro_tamanho_login1 {
            get {
                return ResourceManager.GetString("erro_tamanho_login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A nova senha ter entre 6 e 20 caracteres..
        /// </summary>
        public static string erro_tamanho_nova_senha_min_max {
            get {
                return ResourceManager.GetString("erro_tamanho_nova_senha_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha excedeu o tamanho limite de caracteres!.
        /// </summary>
        public static string erro_tamanho_senha {
            get {
                return ResourceManager.GetString("erro_tamanho_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha deve ter entre 6 e 20 caracteres..
        /// </summary>
        public static string erro_tamanho_senha_min_max {
            get {
                return ResourceManager.GetString("erro_tamanho_senha_min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os campos são obrigatórios..
        /// </summary>
        public static string erro_todos_campos_obrigatorios {
            get {
                return ResourceManager.GetString("erro_todos_campos_obrigatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso bloqueado..
        /// </summary>
        public static string erro_usuario_bloqueado {
            get {
                return ResourceManager.GetString("erro_usuario_bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Inválido.
        /// </summary>
        public static string error_cpf_invalido {
            get {
                return ResourceManager.GetString("error_cpf_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Inválido.
        /// </summary>
        public static string error_email_invalido {
            get {
                return ResourceManager.GetString("error_email_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo em duplicidade na lista para envio.
        /// </summary>
        public static string mensagem_anexo_arquivo_duplicado {
            get {
                return ResourceManager.GetString("mensagem_anexo_arquivo_duplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo enviado com sucesso!.
        /// </summary>
        public static string mensagem_anexo_enviado_sucesso {
            get {
                return ResourceManager.GetString("mensagem_anexo_enviado_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo excluído com sucesso!.
        /// </summary>
        public static string mensagem_anexo_excluido_sucesso {
            get {
                return ResourceManager.GetString("mensagem_anexo_excluido_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Só é permitido o envio de no máximo 5 arquivos anexos por solicitação..
        /// </summary>
        public static string mensagem_anexo_limite_arquivos {
            get {
                return ResourceManager.GetString("mensagem_anexo_limite_arquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum anexo foi selecionado!.
        /// </summary>
        public static string mensagem_anexo_nenhum_anexo_selecionado {
            get {
                return ResourceManager.GetString("mensagem_anexo_nenhum_anexo_selecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo do arquivo deve ser menor ou igual a 10mb.
        /// </summary>
        public static string mensagem_anexo_tamanho_arquivo {
            get {
                return ResourceManager.GetString("mensagem_anexo_tamanho_arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O tamanho máximo permitido de todos os arquivos anexados é de 15mb.
        /// </summary>
        public static string mensagem_anexo_tamanho_arquivos {
            get {
                return ResourceManager.GetString("mensagem_anexo_tamanho_arquivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor informar os dados principais como dados do cliente CPF, dados do pagamento, dados da dívida para que a solicitação seja melhor atendida.
        /// </summary>
        public static string mensagem_campo_descricao {
            get {
                return ResourceManager.GetString("mensagem_campo_descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para realizar a pesquisa ao menos um dos campos deve ser preenchido.
        /// </summary>
        public static string mensagem_dados_pesquisa_invalidos {
            get {
                return ResourceManager.GetString("mensagem_dados_pesquisa_invalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório!.
        /// </summary>
        public static string mensagem_erro_campo_obrigatorio {
            get {
                return ResourceManager.GetString("mensagem_erro_campo_obrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da coluna {0} ({1}) é inválido..
        /// </summary>
        public static string mensagem_erro_coluna_linha {
            get {
                return ResourceManager.GetString("mensagem_erro_coluna_linha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu o seguinte erro ao enviar o anexo: .
        /// </summary>
        public static string mensagem_erro_enviar_anexo {
            get {
                return ResourceManager.GetString("mensagem_erro_enviar_anexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu o seguinte erro ao tentar excluír o anexo:.
        /// </summary>
        public static string mensagem_erro_excluir_anexo {
            get {
                return ResourceManager.GetString("mensagem_erro_excluir_anexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu o seguinte erro ao tentar excluír o anexo:.
        /// </summary>
        public static string mensagem_erro_excluir_anexo1 {
            get {
                return ResourceManager.GetString("mensagem_erro_excluir_anexo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URL requisitada não foi encontrada neste servidor. Se você digitou o endereço (URL) manualmente, por favor verifique novamente a sintaxe do endereço..
        /// </summary>
        public static string mensagem_erro_generico {
            get {
                return ResourceManager.GetString("mensagem_erro_generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um problema ao indexar o arquivo: {0}.
        /// </summary>
        public static string mensagem_erro_indexar_arquivo {
            get {
                return ResourceManager.GetString("mensagem_erro_indexar_arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu uma exceção não esperada na leitura do arquivo: {0}, na linha: {1}.
        /// </summary>
        public static string mensagem_erro_inseperado_leitura_arquivo {
            get {
                return ResourceManager.GetString("mensagem_erro_inseperado_leitura_arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout do arquivo selecionado esta inválido. Favor verificar.
        /// </summary>
        public static string mensagem_erro_layout_arquivo_invalido {
            get {
                return ResourceManager.GetString("mensagem_erro_layout_arquivo_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A linha {0} do arquivo {1} está invalida..
        /// </summary>
        public static string mensagem_erro_linha_arquivo {
            get {
                return ResourceManager.GetString("mensagem_erro_linha_arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login inválido!.
        /// </summary>
        public static string mensagem_erro_login_incorreto {
            get {
                return ResourceManager.GetString("mensagem_erro_login_incorreto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema não pode carregar a planilha, pois o arquivo está fora da nomenclatura padrão..
        /// </summary>
        public static string mensagem_erro_nomeclatura_invalida {
            get {
                return ResourceManager.GetString("mensagem_erro_nomeclatura_invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ticket [{0}] não pode ser atulizado pois está em atendimento..
        /// </summary>
        public static string mensagem_erro_ticket_em_atendimento {
            get {
                return ResourceManager.GetString("mensagem_erro_ticket_em_atendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efetuar nova carga. Arquivo possui mais de 1 hora de criação..
        /// </summary>
        public static string mensagem_erro_timestamp_arquivo_invalido {
            get {
                return ResourceManager.GetString("mensagem_erro_timestamp_arquivo_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo já foi indexado pelo sistema!.
        /// </summary>
        public static string mensagem_info_importacao_indexada_sistema {
            get {
                return ResourceManager.GetString("mensagem_info_importacao_indexada_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A importcao deste arquivo já foi iniciada pelo sistema..
        /// </summary>
        public static string mensagem_info_importacao_iniciada_sistema {
            get {
                return ResourceManager.GetString("mensagem_info_importacao_iniciada_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ticket com número [{0}] não foi encontrado na base de dados..
        /// </summary>
        public static string mensagem_info_tickect_nao_encontrado {
            get {
                return ResourceManager.GetString("mensagem_info_tickect_nao_encontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar processar a ação solicitada, detalhes do erro seguem abaixo:.
        /// </summary>
        public static string mensagem_pagina_erro {
            get {
                return ResourceManager.GetString("mensagem_pagina_erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma Solicitação foi encontrada!.
        /// </summary>
        public static string mensagem_pesquisa_sem_resultado {
            get {
                return ResourceManager.GetString("mensagem_pesquisa_sem_resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação alterada com sucesso!.
        /// </summary>
        public static string mensagem_solicitacao_alterada_sucesso {
            get {
                return ResourceManager.GetString("mensagem_solicitacao_alterada_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação cadastrada com sucesso!.
        /// </summary>
        public static string mensagem_solicitacao_cadastrada_sucesso {
            get {
                return ResourceManager.GetString("mensagem_solicitacao_cadastrada_sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SGCA]: Abertura Solicitação .
        /// </summary>
        public static string mensagem_titulo_abertura_solicitacao {
            get {
                return ResourceManager.GetString("mensagem_titulo_abertura_solicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SGCA]: Solicitação de Acesso ao Sistema SGCA.
        /// </summary>
        public static string mensagem_titulo_acesso {
            get {
                return ResourceManager.GetString("mensagem_titulo_acesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SGCA]:  Aviso de Solicitação Atualizada .
        /// </summary>
        public static string mensagem_titulo_alteracao_solicitacao {
            get {
                return ResourceManager.GetString("mensagem_titulo_alteracao_solicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SGCA]: Senha de Acesso ao sistema.
        /// </summary>
        public static string mensagem_titulo_senha_acesso {
            get {
                return ResourceManager.GetString("mensagem_titulo_senha_acesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O  Valor da Baixa deve ser menor ou igual ao Valor do Crédito.
        /// </summary>
        public static string mensagem_valor_baixa_menor_credito {
            get {
                return ResourceManager.GetString("mensagem_valor_baixa_menor_credito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O  Valor do Débito deve ser menor ou igual ao Valor do Crédito.
        /// </summary>
        public static string mensagem_valor_debito_menor_credito {
            get {
                return ResourceManager.GetString("mensagem_valor_debito_menor_credito", resourceCulture);
            }
        }
    }
}
